name: Release scaling-exercise

on:
  push:
    branches:
      - main
    paths:
      - 'scaling-exercise/**'
      - '.github/workflows/scaling-exercise.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # We need to login so we can later push the image without issues. 
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push calculator
    - name: Build and push calculator
      uses: docker/build-push-action@v2
      with:
        context: scaling-exercise/calculator
        push: true
        tags: devopsdockeruh/scaling-exercise-calculator:latest

    # Build and push compute
    - name: Build and push compute
      uses: docker/build-push-action@v2
      with:
        context: scaling-exercise/compute
        push: true
        tags: devopsdockeruh/scaling-exercise-compute:latest
