name: Release simple-web-service

on:
  push:
    branches:
      - main
    paths:
      - 'simple-web-service/**'
      - '.github/workflows/simple-web-service.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Test different exercises

    # We need to login so we can later push the image without issues. 
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push
    - name: Build and push scratch
      uses: docker/build-push-action@v2
      with:
        context: simple-web-service
        file: simple-web-service/Dockerfile
        push: true
        tags: devopsdockeruh/simple-web-service:latest

    - name: Build and push alpine
      uses: docker/build-push-action@v2
      with:
        context: simple-web-service
        file: simple-web-service/Dockerfile.alpine
        push: true
        tags: devopsdockeruh/simple-web-service:alpine

    - name: Build and push ubuntu
      uses: docker/build-push-action@v2
      with:
        context: simple-web-service
        file: simple-web-service/Dockerfile.ubuntu
        push: true
        tags: devopsdockeruh/simple-web-service:ubuntu

